version: '1'
services:
  db:
    image: postgres
    restart: always
    container_name: easyCartDB
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - 3000:3000
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}

  scrapper:
    build:
      context: ./scrapper
      dockerfile: ./Dockerfile
    container_name: scrapper
    volumes:
      - ./scrapper:/app
    ports:
      - 5000:5000